using BatchDataAccessLibrary.Interfaces;
using BatchDataAccessLibrary.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BatchDataAccessLibrary.Repositories
{
    public class DemoMockMaterialDetailsRepository : IMaterialDetailsRepository
    {

        public List<MaterialDetails> materials = new List<MaterialDetails>();

        public MaterialDetails AddNewFoundMaterial(MaterialDetails material)
        {
            if (!materials.Exists(x => x.Name == material.Name))
            {
                material.MaterialDetailsId = GetNextId();
                materials.Add(material);
            }

            return material;
        }
        private int GetNextId()
        {
            var test = materials.Select(x => x.MaterialDetailsId).Max() + 1;
            return test;
        }

        public bool Any(int id)
        {
            return materials.Any(m => m.MaterialDetailsId == id);
        }

        public async Task<MaterialDetails> FindAsync(int? id)
        {
            Task<MaterialDetails> task = Task.Run(() =>
            {
                return materials.Find(x => x.MaterialDetailsId == id);
            });

            return await task;
        }

        public List<MaterialDetails> GetAllMaterialDetails()
        {
            return materials;
        }

        public double GetAverageWaitTimeOfMaterial(string name)
        {
            return materials.Find(x => x.Name == name).AvgWaitTime;
        }

        public double GetAverageWeighTimeOfMaterial(string name)
        {
            return materials.Find(x => x.Name == name).AvgWeighTime;
        }

        public double GetCostMaterialLoss(string material, double amountUnderOver)
        {
            double costPerKg = materials.Where(x => x.Name == material).Select(x => x.CostPerTon).FirstOrDefault() / 1000;
            return Math.Round(costPerKg * amountUnderOver, 2);
        }

        public List<SelectListItem> GetListOfActiveMaterialsForDropDown()
        {
            List<SelectListItem> output = new List<SelectListItem>();

            foreach (var material in materials.Where(x => x.IsActive == true).OrderBy(x => x.ShortName).ToList())
            {
                output.Add(new SelectListItem { Text = material.ShortName, Value = material.Name });
            }
            return output;
        }

        public List<string> GetMaterialNames()
        {
            return materials.OrderBy(x => x.Name).Select(x => x.Name).ToList();
        }

        public List<string> GetMaterialNamesByShortName()
        {
            return materials.OrderBy(x => x.ShortName).Select(x => x.ShortName).ToList();
        }

        public List<string> GetMaterialNamesThatAreIncludedInMatVar()
        {
            return materials.Where(x => x.IncludeInMatVar == true).Select(x => x.Name).ToList();
        }

        public List<MaterialDetails> GetMaterialsThatNeedDetailsEntering()
        {
            return materials.Where(x => x.NeedsDetailsInput == true).ToList();
        }

        public MaterialDetails GetSingleMaterial(string name)
        {
            return materials.Where(x => x.Name == name).FirstOrDefault();
        }

        public MaterialDetails GetSingleMaterial(int productCode)
        {
            return materials.Where(x => x.ProductCode == productCode).FirstOrDefault();
        }

        public bool IsIncludedInMatVar(string name)
        {
            return materials.Where(x => x.Name == name).Select(x => x.IncludeInMatVar).FirstOrDefault();
        }

        public void LoadMaterialData()
        {
            materials = JsonConvert.DeserializeObject<List<MaterialDetails>>(GetJsonString());
        }

        public void SaveChanges()
        {
            return;
        }

        public Task SaveChangesAsync()
        {
            return Task.Run(() => 1);
        }

        public EntityEntry<MaterialDetails> Update(MaterialDetails materialDetails)
        {
            MaterialDetails existingMaterial = materials.Find(m => m.MaterialDetailsId == materialDetails.MaterialDetailsId);
            existingMaterial.IncludeInMatVar = materialDetails.IncludeInMatVar;
            existingMaterial.IsActive = materialDetails.IsActive;
            existingMaterial.NeedsDetailsInput = materialDetails.NeedsDetailsInput;
            existingMaterial.ParallelGroupOrder = materialDetails.ParallelGroupOrder;
            existingMaterial.ParallelWeighGroup = materialDetails.ParallelWeighGroup;
            existingMaterial.ProductCode = materialDetails.ProductCode;
            existingMaterial.ShortName = materialDetails.ShortName;
            existingMaterial.StartDate = materialDetails.StartDate;
            existingMaterial.EndDate = materialDetails.EndDate;
            existingMaterial.AvgWaitTime = materialDetails.AvgWaitTime;
            existingMaterial.AvgWeighTime = materialDetails.AvgWeighTime;
            existingMaterial.CostPerTon = materialDetails.CostPerTon;
            return null;
        }

       

        private string GetJsonString()
        {
            return @"[
               {
                  'MaterialDetailsId':1,
                  'Name':'Material 1',
                  'ShortName':'Material 1',
                  'ProductCode':50828,
                  'AvgWeighTime':1.17,
                  'AvgWaitTime':0.17,
                  'CostPerTon':2.94,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':3,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':2,
                  'Name':'Material 2',
                  'ShortName':'Material 2',
                  'ProductCode':67661885,
                  'AvgWeighTime':6.37,
                  'AvgWaitTime':0.16,
                  'CostPerTon':20088.18,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':3,
                  'Name':'Material 3',
                  'ShortName':'Material 3',
                  'ProductCode':0,
                  'AvgWeighTime':6.49,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':4,
                  'Name':'Material 4',
                  'ShortName':'Material 4',
                  'ProductCode':9004312,
                  'AvgWeighTime':5.48,
                  'AvgWaitTime':0.15,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':5,
                  'Name':'Material 5',
                  'ShortName':'Material 5',
                  'ProductCode':67630176,
                  'AvgWeighTime':6.68,
                  'AvgWaitTime':0.19,
                  'CostPerTon':13765.6,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':6,
                  'Name':'Material 6',
                  'ShortName':'Material 6',
                  'ProductCode':67630184,
                  'AvgWeighTime':1.86,
                  'AvgWaitTime':0.24,
                  'CostPerTon':9713.95,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':7,
                  'Name':'Material 7',
                  'ShortName':'Material 7',
                  'ProductCode':67734930,
                  'AvgWeighTime':15.39,
                  'AvgWaitTime':0.14,
                  'CostPerTon':19137.79,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':8,
                  'Name':'Material 8',
                  'ShortName':'Material 8',
                  'ProductCode':67335748,
                  'AvgWeighTime':16.62,
                  'AvgWaitTime':0.26,
                  'CostPerTon':23819.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':9,
                  'Name':'Material 9',
                  'ShortName':'Material 9',
                  'ProductCode':9157459,
                  'AvgWeighTime':14.76,
                  'AvgWaitTime':0.15,
                  'CostPerTon':18147.47,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':10,
                  'Name':'Material 10',
                  'ShortName':'Material 10',
                  'ProductCode':9140412,
                  'AvgWeighTime':5.01,
                  'AvgWaitTime':0.13,
                  'CostPerTon':13025.5,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':11,
                  'Name':'Material 11',
                  'ShortName':'Material 11',
                  'ProductCode':67661882,
                  'AvgWeighTime':6.26,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':12,
                  'Name':'Material 12',
                  'ShortName':'Material 12',
                  'ProductCode':8888800,
                  'AvgWeighTime':11.73,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':13,
                  'Name':'Material 13',
                  'ShortName':'Material 13',
                  'ProductCode':67335747,
                  'AvgWeighTime':16.84,
                  'AvgWaitTime':0.14,
                  'CostPerTon':23819.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':14,
                  'Name':'Material 14',
                  'ShortName':'Material 14',
                  'ProductCode':67630179,
                  'AvgWeighTime':10.73,
                  'AvgWaitTime':0.22,
                  'CostPerTon':17867.25,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':15,
                  'Name':'Material 15',
                  'ShortName':'Material 15',
                  'ProductCode':9096226,
                  'AvgWeighTime':5.77,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':16,
                  'Name':'Material 16',
                  'ShortName':'Material 16',
                  'ProductCode':8206225,
                  'AvgWeighTime':2.19,
                  'AvgWaitTime':0.13,
                  'CostPerTon':29191.16,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':6,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':17,
                  'Name':'Material 17',
                  'ShortName':'Material 17',
                  'ProductCode':8948783,
                  'AvgWeighTime':6.97,
                  'AvgWaitTime':0.15,
                  'CostPerTon':500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':18,
                  'Name':'Material 18',
                  'ShortName':'Material 18',
                  'ProductCode':8847783,
                  'AvgWeighTime':7.39,
                  'AvgWaitTime':0.15,
                  'CostPerTon':14436.12,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':19,
                  'Name':'Material 19',
                  'ShortName':'Material 19',
                  'ProductCode':67834376,
                  'AvgWeighTime':8.99,
                  'AvgWaitTime':0.27,
                  'CostPerTon':15810.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':20,
                  'Name':'Material 20',
                  'ShortName':'Material 20',
                  'ProductCode':9232494,
                  'AvgWeighTime':5.43,
                  'AvgWaitTime':0.15,
                  'CostPerTon':12945.27,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':21,
                  'Name':'Material 21',
                  'ShortName':'Material 21',
                  'ProductCode':8896308,
                  'AvgWeighTime':4.46,
                  'AvgWaitTime':0.14,
                  'CostPerTon':1204.65,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':60,
                  'MaxRawTemp':70
               },
               {
                  'MaterialDetailsId':22,
                  'Name':'Material 22',
                  'ShortName':'Material 22',
                  'ProductCode':0,
                  'AvgWeighTime':2.78,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':23,
                  'Name':'Material 23',
                  'ShortName':'Material 23',
                  'ProductCode':8948727,
                  'AvgWeighTime':7.07,
                  'AvgWaitTime':0.22,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':24,
                  'Name':'Material 24',
                  'ShortName':'Material 24',
                  'ProductCode':8726452,
                  'AvgWeighTime':4.6,
                  'AvgWaitTime':0.22,
                  'CostPerTon':2796.14,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':25,
                  'Name':'Material 25',
                  'ShortName':'Material 25',
                  'ProductCode':67661883,
                  'AvgWeighTime':7.07,
                  'AvgWaitTime':0.24,
                  'CostPerTon':20788.46,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':26,
                  'Name':'Material 26',
                  'ShortName':'Material 26',
                  'ProductCode':67661879,
                  'AvgWeighTime':6.34,
                  'AvgWaitTime':0.13,
                  'CostPerTon':21488.75,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':27,
                  'Name':'Material 27',
                  'ShortName':'Material 27',
                  'ProductCode':8883955,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1000.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':28,
                  'Name':'Material 28',
                  'ShortName':'Material 28',
                  'ProductCode':8883954,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':200.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':29,
                  'Name':'MILLING',
                  'ShortName':'Milling',
                  'ProductCode':0,
                  'AvgWeighTime':18.0,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1200.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':30,
                  'Name':'PreWeigher3',
                  'ShortName':'Stream 3',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':31,
                  'Name':'PreWeigher2',
                  'ShortName':'Stream 2',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':32,
                  'Name':'PreWeigher1',
                  'ShortName':'Stream 1',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':33,
                  'Name':'Material 30',
                  'ShortName':'Material 30',
                  'ProductCode':67322276,
                  'AvgWeighTime':19.0,
                  'AvgWaitTime':0.15,
                  'CostPerTon':23325.99,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':34,
                  'Name':'Material 31',
                  'ShortName':'Material 70 Hypo',
                  'ProductCode':68122641,
                  'AvgWeighTime':7.07,
                  'AvgWaitTime':0.59,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':35,
                  'Name':'Material 32',
                  'ShortName':'Material 32',
                  'ProductCode':8988260,
                  'AvgWeighTime':9.43,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':36,
                  'Name':'Material 33',
                  'ShortName':'Material 33',
                  'ProductCode':67188699,
                  'AvgWeighTime':12.72,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17123.89,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':37,
                  'Name':'Material 34',
                  'ShortName':'Material 34',
                  'ProductCode':9232491,
                  'AvgWeighTime':16.25,
                  'AvgWaitTime':0.16,
                  'CostPerTon':18887.69,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':38,
                  'Name':'Material 35',
                  'ShortName':'Material 4',
                  'ProductCode':9004312,
                  'AvgWeighTime':8.78,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17217.01,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':39,
                  'Name':'Material 36',
                  'ShortName':'Material 36',
                  'ProductCode':67630175,
                  'AvgWeighTime':13.21,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17787.64,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':40,
                  'Name':'Material 37',
                  'ShortName':'Material 37',
                  'ProductCode':67661878,
                  'AvgWeighTime':8.07,
                  'AvgWaitTime':0.29,
                  'CostPerTon':18187.4,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':41,
                  'Name':'Material 38',
                  'ShortName':'Material 38',
                  'ProductCode':8921686,
                  'AvgWeighTime':9.53,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':42,
                  'Name':'Material 39',
                  'ShortName':'Material 39',
                  'ProductCode':8988285,
                  'AvgWeighTime':11.1,
                  'AvgWaitTime':0.15,
                  'CostPerTon':17846.12,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':43,
                  'Name':'Material 40',
                  'ShortName':'Material 40',
                  'ProductCode':67631764,
                  'AvgWeighTime':9.26,
                  'AvgWaitTime':0.15,
                  'CostPerTon':13388.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':44,
                  'Name':'Material 41',
                  'ShortName':'Material 41',
                  'ProductCode':67630177,
                  'AvgWeighTime':10.12,
                  'AvgWaitTime':0.15,
                  'CostPerTon':20208.23,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':45,
                  'Name':'Material 42',
                  'ShortName':'Material 42',
                  'ProductCode':67397993,
                  'AvgWeighTime':11.26,
                  'AvgWaitTime':0.16,
                  'CostPerTon':11464.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':46,
                  'Name':'Material 43',
                  'ShortName':'Material 43',
                  'ProductCode':9060339,
                  'AvgWeighTime':12.16,
                  'AvgWaitTime':0.13,
                  'CostPerTon':17147.28,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':47,
                  'Name':'Material 44',
                  'ShortName':'Material 44',
                  'ProductCode':67236646,
                  'AvgWeighTime':15.38,
                  'AvgWaitTime':0.2,
                  'CostPerTon':17287.04,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':48,
                  'Name':'Material 45',
                  'ShortName':'Material 45',
                  'ProductCode':8994437,
                  'AvgWeighTime':10.22,
                  'AvgWaitTime':0.26,
                  'CostPerTon':13935.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':49,
                  'Name':'Material 46',
                  'ShortName':'Material 46',
                  'ProductCode':9140414,
                  'AvgWeighTime':6.21,
                  'AvgWaitTime':0.23,
                  'CostPerTon':12445.08,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':50,
                  'Name':'Material 47',
                  'ShortName':'Material 47',
                  'ProductCode':8738859,
                  'AvgWeighTime':2.17,
                  'AvgWaitTime':0.13,
                  'CostPerTon':2371.42,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':8,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':51,
                  'Name':'Material 48',
                  'ShortName':'Material 48',
                  'ProductCode':8887700,
                  'AvgWeighTime':1.06,
                  'AvgWaitTime':0.1,
                  'CostPerTon':29445.24,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':52,
                  'Name':'Empty PreWeigher2',
                  'ShortName':'Empty PreWeigher2',
                  'ProductCode':0,
                  'AvgWeighTime':6.55,
                  'AvgWaitTime':0.18,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':53,
                  'Name':'Material 49',
                  'ShortName':'Dump Flush',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':54,
                  'Name':'Material 45 E',
                  'ShortName':'Material 45 E',
                  'ProductCode':67726344,
                  'AvgWeighTime':8.35,
                  'AvgWaitTime':0.23,
                  'CostPerTon':13935.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':55,
                  'Name':'Material 51',
                  'ShortName':'Material 51',
                  'ProductCode':8789909,
                  'AvgWeighTime':5.86,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1412.02,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':60,
                  'MaxRawTemp':70
               },
               {
                  'MaterialDetailsId':56,
                  'Name':'Empty PreWeigher4',
                  'ShortName':'Empty PreWeigher4',
                  'ProductCode':0,
                  'AvgWeighTime':1.77,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':57,
                  'Name':'Material 53',
                  'ShortName':'Material 53',
                  'ProductCode':9090409,
                  'AvgWeighTime':1.25,
                  'AvgWaitTime':0.15,
                  'CostPerTon':776.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':1,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':58,
                  'Name':'Material 54',
                  'ShortName':'Material 54',
                  'ProductCode':0,
                  'AvgWeighTime':1.46,
                  'AvgWaitTime':0.31,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':59,
                  'Name':'Empty PreWeigher1',
                  'ShortName':'Empty PreWeigher1',
                  'ProductCode':0,
                  'AvgWeighTime':7.39,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':60,
                  'Name':'PerfumeFlush',
                  'ShortName':'PerfumeFlush',
                  'ProductCode':0,
                  'AvgWeighTime':1.16,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':61,
                  'Name':'Material 57',
                  'ShortName':'Material 57',
                  'ProductCode':9142015,
                  'AvgWeighTime':1.68,
                  'AvgWaitTime':0.3,
                  'CostPerTon':12254.99,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':62,
                  'Name':'Material59 Flush',
                  'ShortName':'Material 59 Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.48,
                  'AvgWaitTime':0.15,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':63,
                  'Name':'Material 59',
                  'ShortName':'Material 59',
                  'ProductCode':8279083,
                  'AvgWeighTime':1.83,
                  'AvgWaitTime':0.14,
                  'CostPerTon':141.43,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':9,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':76,
                  'MaxRawTemp':85
               },
               {
                  'MaterialDetailsId':64,
                  'Name':'Flush 2',
                  'ShortName':'Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.35,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':8,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':65,
                  'Name':'Flush 1',
                  'ShortName':'Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.35,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':7,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':66,
                  'Name':'Flush',
                  'ShortName':'Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.35,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':8,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':67,
                  'Name':'Material 63',
                  'ShortName':'Material 63',
                  'ProductCode':0,
                  'AvgWeighTime':9.98,
                  'AvgWaitTime':1.04,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':2,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':17,
                  'MaxRawTemp':25
               },
               {
                  'MaterialDetailsId':68,
                  'Name':'Material 64',
                  'ShortName':'Material 64',
                  'ProductCode':9095688,
                  'AvgWeighTime':2.39,
                  'AvgWaitTime':0.28,
                  'CostPerTon':2126.17,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':7,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':69,
                  'Name':'ManifoldFlush 1',
                  'ShortName':'ManifoldFlush',
                  'ProductCode':0,
                  'AvgWeighTime':0.98,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':4,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':70,
                  'Name':'ManifoldFlush',
                  'ShortName':'ManifoldFlush',
                  'ProductCode':0,
                  'AvgWeighTime':0.98,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':71,
                  'Name':'Material 67',
                  'ShortName':'Material 67',
                  'ProductCode':0,
                  'AvgWeighTime':9.15,
                  'AvgWaitTime':0.66,
                  'CostPerTon':0.03,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':1,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':72,
                  'Name':'Material 68',
                  'ShortName':'Material 68',
                  'ProductCode':50803,
                  'AvgWeighTime':2.03,
                  'AvgWaitTime':0.18,
                  'CostPerTon':1241.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':4,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':73,
                  'Name':'Empty PreWeigher7',
                  'ShortName':'Empty PreWeigher7',
                  'ProductCode':0,
                  'AvgWeighTime':2.02,
                  'AvgWaitTime':0.22,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':74,
                  'Name':'Material 70',
                  'ShortName':'Material 70',
                  'ProductCode':9140413,
                  'AvgWeighTime':8.99,
                  'AvgWaitTime':0.36,
                  'CostPerTon':14731.2,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':75,
                  'Name':'Material 71',
                  'ShortName':'Material 71',
                  'ProductCode':0,
                  'AvgWeighTime':1.39,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':76,
                  'Name':'Empty PreWeigher5',
                  'ShortName':'Empty PreWeigher5',
                  'ProductCode':0,
                  'AvgWeighTime':2.25,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':77,
                  'Name':'Material 73',
                  'ShortName':'Material 73',
                  'ProductCode':9060335,
                  'AvgWeighTime':15.22,
                  'AvgWaitTime':0.23,
                  'CostPerTon':19357.93,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':78,
                  'Name':'Material 74',
                  'ShortName':'Material 74',
                  'ProductCode':67630180,
                  'AvgWeighTime':2.67,
                  'AvgWaitTime':0.21,
                  'CostPerTon':7703.14,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':79,
                  'Name':'Material 75',
                  'ShortName':'Material 75',
                  'ProductCode':67335745,
                  'AvgWeighTime':15.67,
                  'AvgWaitTime':0.14,
                  'CostPerTon':23819.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':80,
                  'Name':'Material 76',
                  'ShortName':'Material 76',
                  'ProductCode':9096208,
                  'AvgWeighTime':7.92,
                  'AvgWaitTime':0.23,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':81,
                  'Name':'Empty PreWeigher8',
                  'ShortName':'Empty PreWeigher8',
                  'ProductCode':0,
                  'AvgWeighTime':1.38,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':82,
                  'Name':'Empty PreWeigher3',
                  'ShortName':'Empty PreWeigher3',
                  'ProductCode':0,
                  'AvgWeighTime':6.59,
                  'AvgWaitTime':0.2,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':83,
                  'Name':'Material 79',
                  'ShortName':'Material 79',
                  'ProductCode':67419219,
                  'AvgWeighTime':1.4,
                  'AvgWaitTime':0.33,
                  'CostPerTon':9063.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':84,
                  'Name':'Material 80',
                  'ShortName':'Material 80',
                  'ProductCode':8702046,
                  'AvgWeighTime':8.05,
                  'AvgWaitTime':0.24,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':85,
                  'Name':'Material 81',
                  'ShortName':'Material 81',
                  'ProductCode':166805,
                  'AvgWeighTime':3.57,
                  'AvgWaitTime':0.1,
                  'CostPerTon':20094.34,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':86,
                  'Name':'HOT TO PreWeigher9',
                  'ShortName':'Material 63 To PreWeigher9',
                  'ProductCode':0,
                  'AvgWeighTime':1.81,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':87,
                  'Name':'Material 83',
                  'ShortName':'Material 83',
                  'ProductCode':9060337,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1000.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':88,
                  'Name':'CACL TO PreWeigher9',
                  'ShortName':'Calcium To PreWeigher9',
                  'ProductCode':0,
                  'AvgWeighTime':1.61,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':89,
                  'Name':'Material 85',
                  'ShortName':'Material 85',
                  'ProductCode':0,
                  'AvgWeighTime':4.77,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':90,
                  'Name':'Empty PreWeigher9',
                  'ShortName':'Empty PreWeigher9',
                  'ProductCode':0,
                  'AvgWeighTime':2.64,
                  'AvgWaitTime':0.66,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':91,
                  'Name':'Material 87',
                  'ShortName':'Material 87',
                  'ProductCode':67733702,
                  'AvgWeighTime':5.49,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17607.17,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':92,
                  'Name':'Material 88',
                  'ShortName':'Material 88',
                  'ProductCode':9055163,
                  'AvgWeighTime':1.14,
                  'AvgWaitTime':0.14,
                  'CostPerTon':4904.15,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':6,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':93,
                  'Name':'Material 89',
                  'ShortName':'Material 89',
                  'ProductCode':0,
                  'AvgWeighTime':2.39,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':3,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':94,
                  'Name':'Empty PreWeigher6',
                  'ShortName':'Empty PreWeigher6',
                  'ProductCode':0,
                  'AvgWeighTime':1.44,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':95,
                  'Name':'Material 91',
                  'ShortName':'Material 91',
                  'ProductCode':397695,
                  'AvgWeighTime':2.02,
                  'AvgWaitTime':0.1,
                  'CostPerTon':73725.49,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':96,
                  'Name':'Material 92',
                  'ShortName':'Material 92',
                  'ProductCode':213836,
                  'AvgWeighTime':2.85,
                  'AvgWaitTime':0.1,
                  'CostPerTon':20117.5,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':97,
                  'Name':'Material 93',
                  'ShortName':'Material 93',
                  'ProductCode':9232492,
                  'AvgWeighTime':1.3,
                  'AvgWaitTime':0.23,
                  'CostPerTon':10904.44,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':98,
                  'Name':'Material 94',
                  'ShortName':'Material 94',
                  'ProductCode':0,
                  'AvgWeighTime':8.02,
                  'AvgWaitTime':0.27,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':99,
                  'Name':'Material 95',
                  'ShortName':'Sunset Material 45',
                  'ProductCode':9206678,
                  'AvgWeighTime':16.72,
                  'AvgWaitTime':0.24,
                  'CostPerTon':22569.19,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':100,
                  'Name':'Material 96',
                  'ShortName':'Material 96',
                  'ProductCode':67975617,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1000.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':101,
                  'Name':'Material 97',
                  'ShortName':'Material 76 LR',
                  'ProductCode':68152463,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':102,
                  'Name':'Material 98',
                  'ShortName':'Material 98',
                  'ProductCode':68145245,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':103,
                  'Name':'Material 99',
                  'ShortName':'Material 99',
                  'ProductCode':68175411,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':104,
                  'Name':'Material 100',
                  'ShortName':'Material 100',
                  'ProductCode':68146174,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':105,
                  'Name':'Material 101',
                  'ShortName':'Material 25',
                  'ProductCode':68433727,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':106,
                  'Name':'Material 102',
                  'ShortName':'Material 70 Hypo',
                  'ProductCode':68122641,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.01,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':107,
                  'Name':'Material 103',
                  'ShortName':'Material 45 LF',
                  'ProductCode':68336721,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1101,
                  'Name':'Material 104',
                  'ShortName':'Material 104',
                  'ProductCode':68433730,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1102,
                  'Name':'Material 105',
                  'ShortName':'Material 105',
                  'ProductCode':68145259,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1103,
                  'Name':'Material 106',
                  'ShortName':'Material 106',
                  'ProductCode':9166283,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1104,
                  'Name':'Material 107',
                  'ShortName':'Material 70snce LR',
                  'ProductCode':68145253,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               }
            ]";
        }


    }
}
