using BatchDataAccessLibrary.Interfaces;
using BatchDataAccessLibrary.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BatchDataAccessLibrary.Repositories
{
    public class MockMaterialDetailsRepository : IMaterialDetailsRepository
    {

        public List<MaterialDetails> materials = new List<MaterialDetails>();

        public MaterialDetails AddNewFoundMaterial(MaterialDetails material)
        {
            if (!materials.Exists(x => x.Name == material.Name))
            {
                materials.Add(material);
            }

            return material;
        }

        public bool Any(int id)
        {
            return materials.Any(m => m.MaterialDetailsId == id);
        }

        public async Task<MaterialDetails> FindAsync(int? id)
        {
            Task<MaterialDetails> task = Task.Run(() =>
            {
                return materials.Find(x => x.MaterialDetailsId == id);
            });

            return await task;
        }

        public List<MaterialDetails> GetAllMaterialDetails()
        {
            return materials;
        }

        public double GetAverageWaitTimeOfMaterial(string name)
        {
            return materials.Find(x => x.Name == name).AvgWaitTime;
        }

        public double GetAverageWeighTimeOfMaterial(string name)
        {
            return materials.Find(x => x.Name == name).AvgWeighTime;
        }

        public double GetCostMaterialLoss(string material, double amountUnderOver)
        {
            double costPerKg = materials.Where(x => x.Name == material).Select(x => x.CostPerTon).FirstOrDefault() / 1000;
            return Math.Round(costPerKg * amountUnderOver, 2);
        }

        public List<SelectListItem> GetListOfActiveMaterialsForDropDown()
        {
            List<SelectListItem> output = new List<SelectListItem>();

            foreach (var material in materials.Where(x => x.IsActive == true).OrderBy(x => x.ShortName).ToList())
            {
                output.Add(new SelectListItem { Text = material.ShortName, Value = material.Name });
            }
            return output;
        }

        public List<string> GetMaterialNames()
        {
            return materials.OrderBy(x => x.Name).Select(x => x.Name).ToList();
        }

        public List<string> GetMaterialNamesByShortName()
        {
            return materials.OrderBy(x => x.ShortName).Select(x => x.ShortName).ToList();
        }

        public List<string> GetMaterialNamesThatAreIncludedInMatVar()
        {
            return materials.Where(x => x.IncludeInMatVar == true).Select(x => x.Name).ToList();
        }

        public List<MaterialDetails> GetMaterialsThatNeedDetailsEntering()
        {
            return materials.Where(x => x.NeedsDetailsInput == true).ToList();
        }

        public MaterialDetails GetSingleMaterial(string name)
        {
            return materials.Where(x => x.Name == name).FirstOrDefault();
        }

        public MaterialDetails GetSingleMaterial(int productCode)
        {
            return materials.Where(x => x.ProductCode == productCode).FirstOrDefault();
        }

        public bool IsIncludedInMatVar(string name)
        {
            return materials.Where(x => x.Name == name).Select(x => x.IncludeInMatVar).FirstOrDefault();
        }

        public void LoadMaterialData()
        {
            materials = JsonConvert.DeserializeObject<List<MaterialDetails>>(GetJsonString());
        }

        public void SaveChanges()
        {
            return;
        }

        public Task SaveChangesAsync()
        {
            return Task.Run(() => 1);
        }

        public EntityEntry<MaterialDetails> Update(MaterialDetails materialDetails)
        {
            MaterialDetails existingMaterial = materials.Find(m => m.MaterialDetailsId == materialDetails.MaterialDetailsId);
            existingMaterial.IncludeInMatVar = materialDetails.IncludeInMatVar;
            existingMaterial.IsActive = materialDetails.IncludeInMatVar;
            existingMaterial.NeedsDetailsInput = materialDetails.IncludeInMatVar;
            existingMaterial.ParallelGroupOrder = materialDetails.ParallelGroupOrder;
            existingMaterial.ParallelWeighGroup = materialDetails.ParallelWeighGroup;
            existingMaterial.ProductCode = materialDetails.ProductCode;
            existingMaterial.ShortName = materialDetails.ShortName;
            existingMaterial.StartDate = materialDetails.StartDate;
            existingMaterial.EndDate = materialDetails.EndDate;
            existingMaterial.AvgWaitTime = materialDetails.AvgWaitTime;
            existingMaterial.AvgWeighTime = materialDetails.AvgWeighTime;
            existingMaterial.CostPerTon = materialDetails.CostPerTon;
            return null;
        }

        private string GetJsonString()
        {
            return @"[
               {
                  'MaterialDetailsId':1,
                  'Name':'PROXEL FM',
                  'ShortName':'Proxel',
                  'ProductCode':50828,
                  'AvgWeighTime':1.17,
                  'AvgWaitTime':0.17,
                  'CostPerTon':2.94,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':3,
                  'IsActive':true,
                  'NeedsDetailsInput':true,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':2,
                  'Name':'ND 67661885',
                  'ShortName':'Fantasio',
                  'ProductCode':67661885,
                  'AvgWeighTime':6.37,
                  'AvgWaitTime':0.16,
                  'CostPerTon':20088.18,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':3,
                  'Name':'BB CIP',
                  'ShortName':'BigBang CIP Rework',
                  'ProductCode':0,
                  'AvgWeighTime':6.49,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':4,
                  'Name':'BABYGUARD',
                  'ShortName':'Tender Babyguard',
                  'ProductCode':9004312,
                  'AvgWeighTime':5.48,
                  'AvgWaitTime':0.15,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':5,
                  'Name':'ND 67630176',
                  'ShortName':'Ella Enchanted Mod 3',
                  'ProductCode':67630176,
                  'AvgWeighTime':6.68,
                  'AvgWaitTime':0.19,
                  'CostPerTon':13765.6,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':6,
                  'Name':'ODISEA',
                  'ShortName':'Odisea',
                  'ProductCode':67630184,
                  'AvgWeighTime':1.86,
                  'AvgWaitTime':0.24,
                  'CostPerTon':9713.95,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':7,
                  'Name':'ND 67734930',
                  'ShortName':'Lagoon',
                  'ProductCode':67734930,
                  'AvgWeighTime':15.39,
                  'AvgWaitTime':0.14,
                  'CostPerTon':19137.79,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':8,
                  'Name':'ND 67335748',
                  'ShortName':'Renaissance',
                  'ProductCode':67335748,
                  'AvgWeighTime':16.62,
                  'AvgWaitTime':0.26,
                  'CostPerTon':23819.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':9,
                  'Name':'ND 9157459',
                  'ShortName':'Puressence',
                  'ProductCode':9157459,
                  'AvgWeighTime':14.76,
                  'AvgWaitTime':0.15,
                  'CostPerTon':18147.47,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':10,
                  'Name':'ND 9140412',
                  'ShortName':'MJ Cotes',
                  'ProductCode':9140412,
                  'AvgWeighTime':5.01,
                  'AvgWaitTime':0.13,
                  'CostPerTon':13025.5,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':11,
                  'Name':'MACAO',
                  'ShortName':'Macao',
                  'ProductCode':67661882,
                  'AvgWeighTime':6.26,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':12,
                  'Name':'FRAISE BOOST',
                  'ShortName':'Fraise Boost',
                  'ProductCode':8888800,
                  'AvgWeighTime':11.73,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':13,
                  'Name':'ND 67335747',
                  'ShortName':'Balario',
                  'ProductCode':67335747,
                  'AvgWeighTime':16.84,
                  'AvgWaitTime':0.14,
                  'CostPerTon':23819.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':14,
                  'Name':'ALASKA MOD',
                  'ShortName':'Alaska Mod',
                  'ProductCode':67630179,
                  'AvgWeighTime':10.73,
                  'AvgWaitTime':0.22,
                  'CostPerTon':17867.25,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':15,
                  'Name':'ND 9096226',
                  'ShortName':'Softcare BF',
                  'ProductCode':9096226,
                  'AvgWeighTime':5.77,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':16,
                  'Name':'JOJOBA OIL',
                  'ShortName':'Jojo Oil',
                  'ProductCode':8206225,
                  'AvgWeighTime':2.19,
                  'AvgWaitTime':0.13,
                  'CostPerTon':29191.16,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':6,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':17,
                  'Name':'ELECTRISIMO',
                  'ShortName':'Electrisimo',
                  'ProductCode':8948783,
                  'AvgWeighTime':6.97,
                  'AvgWaitTime':0.15,
                  'CostPerTon':500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':18,
                  'Name':'ND 8847783',
                  'ShortName':'Lavendacious',
                  'ProductCode':8847783,
                  'AvgWeighTime':7.39,
                  'AvgWaitTime':0.15,
                  'CostPerTon':14436.12,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':19,
                  'Name':'FRAISE BEAT',
                  'ShortName':'Friase Beat',
                  'ProductCode':67834376,
                  'AvgWeighTime':8.99,
                  'AvgWaitTime':0.27,
                  'CostPerTon':15810.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':20,
                  'Name':'KRYSTAL CLOU',
                  'ShortName':'Krystal Cloud',
                  'ProductCode':9232494,
                  'AvgWeighTime':5.43,
                  'AvgWaitTime':0.15,
                  'CostPerTon':12945.27,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':21,
                  'Name':'FATTY ALC',
                  'ShortName':'Stenol (Cetearyl Alcohol)',
                  'ProductCode':8896308,
                  'AvgWeighTime':4.46,
                  'AvgWaitTime':0.14,
                  'CostPerTon':1204.65,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':60,
                  'MaxRawTemp':70
               },
               {
                  'MaterialDetailsId':22,
                  'Name':'NI MANIF FLU',
                  'ShortName':'NI Manifold Flush',
                  'ProductCode':0,
                  'AvgWeighTime':2.78,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':23,
                  'Name':'ND 8948727',
                  'ShortName':'Helsinki 84',
                  'ProductCode':8948727,
                  'AvgWeighTime':7.07,
                  'AvgWaitTime':0.22,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':24,
                  'Name':'NONIONIC',
                  'ShortName':'Luthensol (NonIonic)',
                  'ProductCode':8726452,
                  'AvgWeighTime':4.6,
                  'AvgWaitTime':0.22,
                  'CostPerTon':2796.14,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':25,
                  'Name':'ND 67661883',
                  'ShortName':'Spa Delight',
                  'ProductCode':67661883,
                  'AvgWeighTime':7.07,
                  'AvgWaitTime':0.24,
                  'CostPerTon':20788.46,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':26,
                  'Name':'ND 67661879',
                  'ShortName':'Java Wood',
                  'ProductCode':67661879,
                  'AvgWeighTime':6.34,
                  'AvgWaitTime':0.13,
                  'CostPerTon':21488.75,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':27,
                  'Name':'JILLZ',
                  'ShortName':'Jillz',
                  'ProductCode':8883955,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1000.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':28,
                  'Name':'BLOSSOM CAP',
                  'ShortName':'Blossom Cap',
                  'ProductCode':8883954,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':200.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':29,
                  'Name':'MILLING',
                  'ShortName':'Milling',
                  'ProductCode':0,
                  'AvgWeighTime':18.0,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1200.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':30,
                  'Name':'V303',
                  'ShortName':'Stream 3',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':31,
                  'Name':'V203',
                  'ShortName':'Stream 2',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':32,
                  'Name':'V103',
                  'ShortName':'Stream 1',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':33,
                  'Name':'ND 67322276',
                  'ShortName':'Babybear Intense',
                  'ProductCode':67322276,
                  'AvgWeighTime':19.0,
                  'AvgWaitTime':0.15,
                  'CostPerTon':23325.99,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':34,
                  'Name':'ND 68122641',
                  'ShortName':'Puresse Hypo',
                  'ProductCode':68122641,
                  'AvgWeighTime':7.07,
                  'AvgWaitTime':0.59,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':35,
                  'Name':'ND 8988260',
                  'ShortName':'Cashmere Glow',
                  'ProductCode':8988260,
                  'AvgWeighTime':9.43,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':36,
                  'Name':'ND 67188699',
                  'ShortName':'Levendiva',
                  'ProductCode':67188699,
                  'AvgWeighTime':12.72,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17123.89,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':37,
                  'Name':'ND 9232491',
                  'ShortName':'Cosmopoltan',
                  'ProductCode':9232491,
                  'AvgWeighTime':16.25,
                  'AvgWaitTime':0.16,
                  'CostPerTon':18887.69,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':38,
                  'Name':'ND 9004312',
                  'ShortName':'Tender Babyguard',
                  'ProductCode':9004312,
                  'AvgWeighTime':8.78,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17217.01,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':39,
                  'Name':'ND 67630175',
                  'ShortName':'Silk Cloud',
                  'ProductCode':67630175,
                  'AvgWeighTime':13.21,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17787.64,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':40,
                  'Name':'ND 67661878',
                  'ShortName':'Sun Blossom',
                  'ProductCode':67661878,
                  'AvgWeighTime':8.07,
                  'AvgWaitTime':0.29,
                  'CostPerTon':18187.4,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':41,
                  'Name':'ND 8921686',
                  'ShortName':'Fruit Fever',
                  'ProductCode':8921686,
                  'AvgWeighTime':9.53,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':42,
                  'Name':'ND 8988285',
                  'ShortName':'Lady Goddess',
                  'ProductCode':8988285,
                  'AvgWeighTime':11.1,
                  'AvgWaitTime':0.15,
                  'CostPerTon':17846.12,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':43,
                  'Name':'ND 67631764',
                  'ShortName':'Elegant Coco Evo',
                  'ProductCode':67631764,
                  'AvgWeighTime':9.26,
                  'AvgWaitTime':0.15,
                  'CostPerTon':13388.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':44,
                  'Name':'ND 67630177',
                  'ShortName':'Tango Punch Mod',
                  'ProductCode':67630177,
                  'AvgWeighTime':10.12,
                  'AvgWaitTime':0.15,
                  'CostPerTon':20208.23,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':45,
                  'Name':'ND 67397993',
                  'ShortName':'Skywalking Bellatrix 7',
                  'ProductCode':67397993,
                  'AvgWeighTime':11.26,
                  'AvgWaitTime':0.16,
                  'CostPerTon':11464.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':46,
                  'Name':'ND 9060339',
                  'ShortName':'Yellow Diamond',
                  'ProductCode':9060339,
                  'AvgWeighTime':12.16,
                  'AvgWaitTime':0.13,
                  'CostPerTon':17147.28,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':47,
                  'Name':'ND 67236646',
                  'ShortName':'Fantasia',
                  'ProductCode':67236646,
                  'AvgWeighTime':15.38,
                  'AvgWaitTime':0.2,
                  'CostPerTon':17287.04,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':48,
                  'Name':'GOA FLOWER',
                  'ShortName':'Goa Flower',
                  'ProductCode':8994437,
                  'AvgWeighTime':10.22,
                  'AvgWaitTime':0.26,
                  'CostPerTon':13935.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':49,
                  'Name':'BLUE LEGEND',
                  'ShortName':'Blue Legend',
                  'ProductCode':9140414,
                  'AvgWeighTime':6.21,
                  'AvgWaitTime':0.23,
                  'CostPerTon':12445.08,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':50,
                  'Name':'DMDMH',
                  'ShortName':'DMDMH',
                  'ProductCode':8738859,
                  'AvgWeighTime':2.17,
                  'AvgWaitTime':0.13,
                  'CostPerTon':2371.42,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':8,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':51,
                  'Name':'VIOLET DYE',
                  'ShortName':'Violet Dye',
                  'ProductCode':8887700,
                  'AvgWeighTime':1.06,
                  'AvgWaitTime':0.1,
                  'CostPerTon':29445.24,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':52,
                  'Name':'Empty V203',
                  'ShortName':'Empty V203',
                  'ProductCode':0,
                  'AvgWeighTime':6.55,
                  'AvgWaitTime':0.18,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':53,
                  'Name':'DUMP FLUSH',
                  'ShortName':'Dump Flush',
                  'ProductCode':0,
                  'AvgWeighTime':0.0,
                  'AvgWaitTime':0.0,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':54,
                  'Name':'GOA FLOWER E',
                  'ShortName':'Goa Flower E',
                  'ProductCode':67726344,
                  'AvgWeighTime':8.35,
                  'AvgWaitTime':0.23,
                  'CostPerTon':13935.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':55,
                  'Name':'SOFTQUAT',
                  'ShortName':'Softquat',
                  'ProductCode':8789909,
                  'AvgWeighTime':5.86,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1412.02,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':60,
                  'MaxRawTemp':70
               },
               {
                  'MaterialDetailsId':56,
                  'Name':'Empty V102',
                  'ShortName':'Empty V102',
                  'ProductCode':0,
                  'AvgWeighTime':1.77,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':57,
                  'Name':'Calc Chlorid',
                  'ShortName':'Calcium Chloride',
                  'ProductCode':9090409,
                  'AvgWeighTime':1.25,
                  'AvgWaitTime':0.15,
                  'CostPerTon':776.67,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':1,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':58,
                  'Name':'HOT FLUSH',
                  'ShortName':'Hot Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.46,
                  'AvgWaitTime':0.31,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':59,
                  'Name':'Empty V103',
                  'ShortName':'Empty V103',
                  'ProductCode':0,
                  'AvgWeighTime':7.39,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':60,
                  'Name':'EPERF FLUSH',
                  'ShortName':'Eperf Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.16,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':61,
                  'Name':'SWISS POP',
                  'ShortName':'Swiss Pop',
                  'ProductCode':9142015,
                  'AvgWeighTime':1.68,
                  'AvgWaitTime':0.3,
                  'CostPerTon':12254.99,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':62,
                  'Name':'HCL FLUSH',
                  'ShortName':'HCL Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.48,
                  'AvgWaitTime':0.15,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':63,
                  'Name':'HCL',
                  'ShortName':'HCL',
                  'ProductCode':8279083,
                  'AvgWeighTime':1.83,
                  'AvgWaitTime':0.14,
                  'CostPerTon':141.43,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':9,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':64,
                  'Name':'MINORS FLUSH2',
                  'ShortName':'Minors Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.35,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':8,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':65,
                  'Name':'MINORS FLUSH1',
                  'ShortName':'Minors Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.35,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':7,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':66,
                  'Name':'MINORS FLUSH',
                  'ShortName':'Minors Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.35,
                  'AvgWaitTime':0.16,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':8,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':67,
                  'Name':'HOT WTR',
                  'ShortName':'Hot Water',
                  'ProductCode':0,
                  'AvgWeighTime':9.98,
                  'AvgWaitTime':1.04,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':2,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':76,
                  'MaxRawTemp':85
               },
               {
                  'MaterialDetailsId':68,
                  'Name':'ANTIFOAM',
                  'ShortName':'Antifoam',
                  'ProductCode':9095688,
                  'AvgWeighTime':2.39,
                  'AvgWaitTime':0.28,
                  'CostPerTon':2126.17,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':7,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':69,
                  'Name':'DEQ/CaCl MAN1',
                  'ShortName':'Dequest / Calcium Manifold Flush',
                  'ProductCode':0,
                  'AvgWeighTime':0.98,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':4,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':70,
                  'Name':'DEQ/CaCl MAN',
                  'ShortName':'Dequest / Calcium Manifold Flush',
                  'ProductCode':0,
                  'AvgWeighTime':0.98,
                  'AvgWaitTime':0.17,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':71,
                  'Name':'COLD WTR',
                  'ShortName':'Cold Water',
                  'ProductCode':0,
                  'AvgWeighTime':9.15,
                  'AvgWaitTime':0.66,
                  'CostPerTon':0.03,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':1,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00',
                  'MinRawTemp':17,
                  'MaxRawTemp':25
               },
               {
                  'MaterialDetailsId':72,
                  'Name':'DEQUEST',
                  'ShortName':'Dequest',
                  'ProductCode':50803,
                  'AvgWeighTime':2.03,
                  'AvgWaitTime':0.18,
                  'CostPerTon':1241.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':1,
                  'ParallelGroupOrder':4,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':73,
                  'Name':'Empty V212',
                  'ShortName':'Empty V212',
                  'ProductCode':0,
                  'AvgWeighTime':2.02,
                  'AvgWaitTime':0.22,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':74,
                  'Name':'WHITE PERF',
                  'ShortName':'Puresse',
                  'ProductCode':9140413,
                  'AvgWeighTime':8.99,
                  'AvgWaitTime':0.36,
                  'CostPerTon':14731.2,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':75,
                  'Name':'PERF FLUSH',
                  'ShortName':'Perf Flush',
                  'ProductCode':0,
                  'AvgWeighTime':1.39,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':76,
                  'Name':'Empty V112',
                  'ShortName':'Empty V112',
                  'ProductCode':0,
                  'AvgWeighTime':2.25,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':77,
                  'Name':'STUDIO 54',
                  'ShortName':'Studio 54',
                  'ProductCode':9060335,
                  'AvgWeighTime':15.22,
                  'AvgWaitTime':0.23,
                  'CostPerTon':19357.93,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':78,
                  'Name':'PARADISE',
                  'ShortName':'Paradise Falls',
                  'ProductCode':67630180,
                  'AvgWeighTime':2.67,
                  'AvgWaitTime':0.21,
                  'CostPerTon':7703.14,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':79,
                  'Name':'ND 67335745',
                  'ShortName':'Paris Shimmer',
                  'ProductCode':67335745,
                  'AvgWeighTime':15.67,
                  'AvgWaitTime':0.14,
                  'CostPerTon':23819.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':80,
                  'Name':'SUN PERF',
                  'ShortName':'Jupiter',
                  'ProductCode':9096208,
                  'AvgWeighTime':7.92,
                  'AvgWaitTime':0.23,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':81,
                  'Name':'Empty V302',
                  'ShortName':'Empty V302',
                  'ProductCode':0,
                  'AvgWeighTime':1.38,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':82,
                  'Name':'Empty V303',
                  'ShortName':'Empty V303',
                  'ProductCode':0,
                  'AvgWeighTime':6.59,
                  'AvgWaitTime':0.2,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':83,
                  'Name':'JAZZ',
                  'ShortName':'Jazz',
                  'ProductCode':67419219,
                  'AvgWeighTime':1.4,
                  'AvgWaitTime':0.33,
                  'CostPerTon':9063.7,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':84,
                  'Name':'ND 8702046',
                  'ShortName':'Angelina Boost',
                  'ProductCode':8702046,
                  'AvgWeighTime':8.05,
                  'AvgWaitTime':0.24,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':85,
                  'Name':'BLUE DYE',
                  'ShortName':'Blue Dye',
                  'ProductCode':166805,
                  'AvgWeighTime':3.57,
                  'AvgWaitTime':0.1,
                  'CostPerTon':20094.34,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':86,
                  'Name':'HOT TO V906',
                  'ShortName':'Hot Water To V906',
                  'ProductCode':0,
                  'AvgWeighTime':1.81,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':87,
                  'Name':'NIAGARA',
                  'ShortName':'Niagara Falls',
                  'ProductCode':9060337,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1000.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':88,
                  'Name':'CACL TO V906',
                  'ShortName':'Calcium To V906',
                  'ProductCode':0,
                  'AvgWeighTime':1.61,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':89,
                  'Name':'BB PRODRWK',
                  'ShortName':'BigBang Product Rework',
                  'ProductCode':0,
                  'AvgWeighTime':4.77,
                  'AvgWaitTime':0.11,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':90,
                  'Name':'Empty V906',
                  'ShortName':'Empty V906',
                  'ProductCode':0,
                  'AvgWeighTime':2.64,
                  'AvgWaitTime':0.66,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':91,
                  'Name':'ND 67733702',
                  'ShortName':'Scooby Punch',
                  'ProductCode':67733702,
                  'AvgWeighTime':5.49,
                  'AvgWaitTime':0.14,
                  'CostPerTon':17607.17,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':92,
                  'Name':'MICROCARE',
                  'ShortName':'Microcare (MIT)',
                  'ProductCode':9055163,
                  'AvgWeighTime':1.14,
                  'AvgWaitTime':0.14,
                  'CostPerTon':4904.15,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':6,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':93,
                  'Name':'DYE FLUSH',
                  'ShortName':'Dye Flush',
                  'ProductCode':0,
                  'AvgWeighTime':2.39,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':3,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':94,
                  'Name':'Empty V202',
                  'ShortName':'Empty V202',
                  'ProductCode':0,
                  'AvgWeighTime':1.44,
                  'AvgWaitTime':0.12,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':5,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':95,
                  'Name':'YELL DYE',
                  'ShortName':'Yellow Dye',
                  'ProductCode':397695,
                  'AvgWeighTime':2.02,
                  'AvgWaitTime':0.1,
                  'CostPerTon':73725.49,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':96,
                  'Name':'PINK DYE',
                  'ShortName':'Pink Dye',
                  'ProductCode':213836,
                  'AvgWeighTime':2.85,
                  'AvgWaitTime':0.1,
                  'CostPerTon':20117.5,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':2,
                  'ParallelGroupOrder':2,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':97,
                  'Name':'ESTRELLA',
                  'ShortName':'Estrella',
                  'ProductCode':9232492,
                  'AvgWeighTime':1.3,
                  'AvgWaitTime':0.23,
                  'CostPerTon':10904.44,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':98,
                  'Name':'WASHINGS RWK',
                  'ShortName':'Washings Rework',
                  'ProductCode':0,
                  'AvgWeighTime':8.02,
                  'AvgWaitTime':0.27,
                  'CostPerTon':1500.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':99,
                  'Name':'ND 9206678',
                  'ShortName':'Sunset Goa Flower',
                  'ProductCode':9206678,
                  'AvgWeighTime':16.72,
                  'AvgWaitTime':0.24,
                  'CostPerTon':22569.19,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':100,
                  'Name':'pot/sorb',
                  'ShortName':'Potassium Sorbate',
                  'ProductCode':67975617,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1000.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':101,
                  'Name':'JUPITER',
                  'ShortName':'Jupiter LR',
                  'ProductCode':68152463,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':102,
                  'Name':'NEW LEGEND',
                  'ShortName':'New Legend LR',
                  'ProductCode':68145245,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':103,
                  'Name':'ND 68175411',
                  'ShortName':'Fig Milk',
                  'ProductCode':68175411,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':104,
                  'Name':'ALPEN POP',
                  'ShortName':'Alpen Popscent',
                  'ProductCode':68146174,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':105,
                  'Name':'ND 68433727',
                  'ShortName':'Spa Delight',
                  'ProductCode':68433727,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':106,
                  'Name':'PURESSE HYPO',
                  'ShortName':'Puresse Hypo',
                  'ProductCode':68122641,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.01,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':107,
                  'Name':'ND 68336721',
                  'ShortName':'Goa Flower LF',
                  'ProductCode':68336721,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1101,
                  'Name':'ND 68433730',
                  'ShortName':'Honeysuckle LF',
                  'ProductCode':68433730,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1102,
                  'Name':'ND 68145259',
                  'ShortName':'Silhouette LR',
                  'ProductCode':68145259,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1103,
                  'Name':'ND 9166283',
                  'ShortName':'Honeysuckle Haloscent',
                  'ProductCode':9166283,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':false,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':false,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               },
               {
                  'MaterialDetailsId':1104,
                  'Name':'ND 68145253',
                  'ShortName':'Puressesnce LR',
                  'ProductCode':68145253,
                  'AvgWeighTime':0.1,
                  'AvgWaitTime':0.1,
                  'CostPerTon':1.0,
                  'IncludeInMatVar':true,
                  'ParallelWeighGroup':0,
                  'ParallelGroupOrder':0,
                  'IsActive':true,
                  'NeedsDetailsInput':false,
                  'StartDate':'0001-01-01T00:00:00',
                  'EndDate':'0001-01-01T00:00:00'
               }
            ]";
        }


    }
}
